{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cellbase.serviceAccountName" . }}
  labels:
{{ include "cellbase.labels" . | nindent 4 }}
{{- end -}}
